
var ratingModal = [
  '<div class="modal fade modals" id="ratingModal" tabindex="-1" role="dialog" aria-hidden="true">',
  '<div class="modal-dialog modal-dialog-centered modals__dialog modals__dialog--md">',
  '<div class="modal-content modals__content">',
  '<div class="modal-header modals__header">',
  '<h5 class="modal-title modals__title">Спасибо за вашу оценку!</h5>',
  '<a class="close modals__close" href="#" data-dismiss="modal" aria-label="Close">',
  '<svg class="modals__close-icon" width="14" height="14"><use xlink:href="img/sprite-svg.svg#modals__close"></use></svg>',
  '</a>',
  '</div>',
  '<div class="modal-body modals__body">',
  '<p class="modals__text">Вы можете поделиться данным купоном со своими друзьями в социальных сетях!</p>',
  '<div class="socials modals__socials">',
  '<ul class="socials__list">',
  '<li class="socials__item">',
  '<a class="socials__link" href="#" title="facebook">',
  '<svg class="socials__icon" width="26" height="26"><use xlink:href="img/sprite-svg.svg#socials__fb"></use></svg>',
  '</a>',
  '</li>',
  '<li class="socials__item">',
  '<a class="socials__link" href="#" title="instagram">',
  '<svg class="socials__icon" width="26" height="26"><use xlink:href="img/sprite-svg.svg#socials__inst"></use></svg>',
  '</a>',
  '</li>',
  '<li class="socials__item socials__item-fb">',
  '<a class="socials__link" href="#" title="vkontakte">',
  '<svg class="socials__icon" width="26" height="26"><use xlink:href="img/sprite-svg.svg#socials__vk"></use></svg>',
  '</a>',
  '</li>',
  '</ul>',
  '</div>',
  '<div class="modals__btn-block">',
  '<button class="modals__btn modals__btn-close" data-dismiss="modal" aria-label="Close">Закрыть</button>',
  '</div>',
  '</div>',
  '</div>',
  '</div>',
  '</div>'
].join('');

var reviewModal = [
  '<div class="modal fade modals" id="reviewModal" tabindex="-1" role="dialog" aria-hidden="true">',
  '<div class="modal-dialog modal-dialog-centered modals__dialog modals__dialog--md">',
  '<div class="modal-content modals__content">',
  '<div class="modal-header modals__header">',
  '<h5 class="modal-title modals__title">Спасибо за ваш отзыв!</h5>',
  '<a class="close modals__close" href="#" data-dismiss="modal" aria-label="Close">',
  '<svg class="modals__close-icon" width="14" height="14"><use xlink:href="img/sprite-svg.svg#modals__close"></use></svg>',
  '</a>',
  '</div>',
  '<div class="modal-body modals__body">',
  '<p class="modals__text">Вы можете поделиться данным купоном со своими друзьями в социальных сетях!</p>',
  '<div class="socials modals__socials">',
  '<ul class="socials__list">',
  '<li class="socials__item">',
  '<a class="socials__link" href="#" title="facebook">',
  '<svg class="socials__icon" width="26" height="26"><use xlink:href="img/sprite-svg.svg#socials__fb"></use></svg>',
  '</a>',
  '</li>',
  '<li class="socials__item">',
  '<a class="socials__link" href="#" title="instagram">',
  '<svg class="socials__icon" width="26" height="26"><use xlink:href="img/sprite-svg.svg#socials__inst"></use></svg>',
  '</a>',
  '</li>',
  '<li class="socials__item socials__item-fb">',
  '<a class="socials__link" href="#" title="vkontakte">',
  '<svg class="socials__icon" width="26" height="26"><use xlink:href="img/sprite-svg.svg#socials__vk"></use></svg>',
  '</a>',
  '</li>',
  '</ul>',
  '</div>',
  '<div class="modals__btn-block">',
  '<button class="modals__btn modals__btn-close" data-dismiss="modal" aria-label="Close">Закрыть</button>',
  '</div>',
  '</div>',
  '</div>',
  '</div>',
  '</div>'
].join('');

var warnDelModal = [
  '<div class="modal fade modals" id="warnDelModal" tabindex="-1" role="dialog" aria-hidden="true">',
  '<div class="modal-dialog modal-dialog-centered modals__dialog modals__dialog--md">',
  '<div class="modal-content modals__content">',
  '<div class="modal-header modals__header">',
  '<h5 class="modal-title modals__title">Вы уверены, что хотите удалить данный купон из избранного ?</h5>',
  '<a class="close modals__close" href="#" data-dismiss="modal" aria-label="Close">',
  '<svg class="modals__close-icon" width="14" height="14"><use xlink:href="img/sprite-svg.svg#modals__close"></use></svg>',
  '</a>',
  '</div>',
  '<div class="modal-body modals__body">',
  '<div class="modals__btn-block">',
  '<button class="modals__btn">Да</button>',
  '<button class="modals__btn modals__btn--gray" data-dismiss="modal" aria-label="Close">Отмена</button>',
  '</div>',
  '</div>',
  '</div>',
  '</div>',
  '</div>'
].join('');
